[build]
  publish = "public"
  command = "echo 'Deploying public directory'"

[dev]
  framework = "#static"
  publish = "public"

# Proxy /api to functions
[[redirects]]
  from = "/api/renewrx"
  to = "/.netlify/functions/renewrx"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
